amp: true
augment: true
batch: 8
cache: false
close_mosaic: 10
copy_paste: 0.1
data: data/dataset.yaml
degrees: 0.0
device: 0
epochs: 300
exist_ok: false
fliplr: 0.5
flipud: 0.0
half: false
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
imgsz: 640
lr0: 0.001
lrf: 0.01
mixup: 0.1
mode: train
model: yolov8n.pt
momentum: 0.937
mosaic: 1.0
name: game_char_train
nbs: 64
optimizer: AdamW
patience: 80
perspective: 0.0
plots: true
pretrained: true
project: runs/train
resume: false
save: true
save_json: false
save_period: 10
scale: 0.5
shear: 0.0
split: val
task: detect
translate: 0.1
val: true
weight_decay: 0.0005
workers: 4
